version: "3"

services:
  php:
    image: fsilva/php:7.2
    volumes:
      - ./:/var/www/app
    ports:
      - 8888:80
    environment:
      - USE_XDEBUG=yes
      - WEBROOT=public

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=System32
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=project